//
//  CircleView.h
//  Adept_iOS
//
//  Created by Martin Kuvandzhiev on 3/28/16.
//  Copyright (c) 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface CircleView : UIView

@property (nonatomic, assign) NSInteger strokeWidth;
@property (nonatomic, strong) UIColor * strokeColor;

// Drawing Methods
- (void)drawCanvas2WithInsideTest: (NSString*)insideTest;

@end
