//
//  CircleView.h
//  Adept_iOS
//
//  Created by Martin Kuvandzhiev on 3/28/16.
//  Copyright (c) 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface CircleView : UIView

@property (nonatomic, assign) NSInteger strokeWidth;
@property (nonatomic, strong) UIColor * strokeColor;
@property (nonatomic, strong) NSString * textString;
@property (nonatomic, assign) NSInteger fontSize;


// Drawing Methods
- (void)drawCanvas2WithInsideText: (NSString*)insideText;

@end
